### ISSUE TITLE
Create Role Definition Permission to Scope relationship

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#123]
Azure Role Definitions enumerate permissions using four fields:
```
"permissions": [
  {
    "actions": [
      "*"
    ],
    "notActions": [
      "Microsoft.Authorization/*/Delete",
      "Microsoft.Authorization/*/Write",
      "Microsoft.Authorization/elevateAccess/Action",
      "Microsoft.Blueprint/blueprintAssignments/write",
      "Microsoft.Blueprint/blueprintAssignments/delete"
    ],
    "dataActions": [],
    "notDataActions": []
  }
]
```

**Comment by ndowmon** [comment]
These relationships should be described using `ALLOWS` relationships for `actions` and `dataActions`. 

There is no `DENIES` relationship class. I propose adding this to the data model and using `DENIES` for `notActions` and `notDataActions`.

**Comment by aiwilliams** [comment]
@erkangz I notice in the AWS integration that there are only `ALLOWS` relationships produced from `AccessPolicy` raw data, and it says in the docs:

> This creates permission relationships from an IAM policy (including both managed policies and inline polices -- i.e. aws_iam_user_policy, aws_iam_group_policy and aws_iam_role_policy) -- to other AWS entities based on the actions and resources specified by the policy document.

[The code in the AWS integration](https://bitbucket.org/jupiterone/jupiter-integration-aws/src/db4db5d6c8d0d529401473705eee9a02819332d1/src/integration-aws/iam/converters.ts?at=master#lines-651) that processes the policies shows this documentation is correct.

Do you think we would ever want to process Deny statements? I could imagine that to be useful where we want to prove that a Deny is in place, but perhaps we can skip that type of relationship in the Azure integration for now as well?

**Comment by erkangz** [comment]
We do want to process Deny statements at some point. It's fine to start with Allow statements first. 

When we do, it's important to do it according to the provider behavior and account for the net results of both allows and denies. In AWS, for example, denies always take precedence regardless of order in the policy.
