### ISSUE TITLE
Question-driven development: Azure Permissions

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#127]
I'm trying to figure out the best way to add entities/relationships so that we can answer useful questions for azure users.

Given the following goal: 
**Find all azure principals that have the ability to delete key vaults in the `ndowmon-j1dev` key vault**

Pseudocode:
```
FIND principal (user, user group, or service principal) \\ could be any of the three
  THAT IS ASSIGNED roleDefinition
  THAT (ALLOWS?) scope (management group, subscription, resource group, or resource) 
  WHERE roleDefinition.notAllows !== Microsoft.KeyVault/vaults/delete and 
        roleDefinition.allows === Microsoft.KeyVault/vaults/delete and
        resource.name === ndowmon-j1dev
```

```
FIND (azure_user|azure_user_group|azure_service_principal)
   THAT ASSIGNED azure_role_definition
   THAT ALLOWS (
      azure_keyvault WITH name = key-vault-id OR
      azure_resource_group THAT HAS azure_keyvault WITH name = key-vault-id OR
      azure_subscription THAT HAS azure_resource_group THAT HAS azure_keyvault WITH name = key-vault-id
   )
   WHERE 
      azure_role_definition.notAllows !== (
         * OR 
         */delete OR 
         Microsoft.KeyVault/*/delete OR 
         Microsoft.KeyVault/vaults/delete
      ) AND 
      azure_role_definition.allows === (
         * OR
         */delete OR
         Microsoft.KeyVault/*/delete OR 
         Microsoft.KeyVault/vaults/delete
      )
```

Questions:
1. Should the services on azure_role_definition.allows become an entity? I think they should just be fields on azure_role_definition but maybe it would be better to say something like `THAT ALLOWS Microsoft.KeyVault WITH notAllows !== (* OR */delete OR vaults/delete) AND allows == (* OR */delete OR vaults/delete`.
1. Does the J1QL allow for a more elegant parsing syntax so that we wouldn't need to use `(* OR */delete ...)` for string matching these RBAC permissions?
1. Does J1QL implement any traversal shortcuts for the target scope (keyvault, resource group or subscription)? Something like the [* (0 or more)](https://chortle.ccsu.edu/FiniteAutomata/Section07/sect07_16.html) quantifier in regular expressions, e.g. `THAT ALLOWS (* THAT HAS)* azure_keyvault WITH name = key-vault-id`.
1. Does the relationship `ALLOWS` make sense for `azure_role_definition --ALLOWS--> (azure_subscription|azure_resource_group|<azure_resource (azure_keyvault, etc...)>)`

As a comparison, here's a query to look at _specific_ access to an IAM resource:
**EDIT**: This query is "Which users have access to production data stores via cross-account IAM assume role trusts?"
```
Find User as user 
   that ASSIGNED aws_iam_role as assignedRole 
   that TRUSTS aws_iam_role as crossAcctRole 
   that ASSIGNED AccessPolicy as policy 
   that ALLOWS as permission DataStore with tag.Production=true as ds 
return 
   user._type, 
   user.displayName, 
   assignedRole.tag.AccountName, 
   assignedRole.displayName, 
   crossAcctRole.tag.AccountName, 
   crossAcctRole.displayName, 
   policy.displayName, 
   permission.displayName, 
   permission.actions, 
   permission.resources, 
   ds.tag.AccountName, 
   ds._type, 
   ds.displayName, 
   ds.classification, 
   ds.encrypted, 
   ds.webLink
```

**Comment by ndowmon** [comment]
Given the following role assignments:

```
/// scope = subscription d3803fd6-2ba4-4286-80aa-f3d613ad59a7
{
  id: '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/providers/Microsoft.Authorization/roleAssignments/10000000-0000-0000-0000-000000000000',
  name: '10000000-0000-0000-0000-000000000000',
  type: 'Microsoft.Authorization/roleAssignments',
  scope: '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7',
  roleDefinitionId: '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/providers/Microsoft.Authorization/roleDefinitions/8bfcfc94-cf28-d595-8e3d-851a1eb7c8fa',
  principalId: '64242f8f-67ee-4f0c-b644-0766b42e8e91',
  principalType: 'ServicePrincipal'
}

/// scope = resource group j1dev
{
  id: '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/resourceGroups/j1dev/providers/Microsoft.Authorization/roleAssignments/20000000-0000-0000-0000-000000000000',
  name: '20000000-0000-0000-0000-000000000000',
  type: 'Microsoft.Authorization/roleAssignments',
  scope: '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/resourceGroups/j1dev',
  roleDefinitionId: '/subscriptions/d3803fd6-2ba4-4286-80aa-f3d613ad59a7/providers/Microsoft.Authorization/roleDefinitions/8bfcfc94-cf28-d595-8e3d-851a1eb7c8fa',
  principalId: '64242f8f-67ee-4f0c-b644-0766b42e8e91',
  principalType: 'ServicePrincipal'
}

```

**Comment by ndowmon** [comment]
Per conversation earlier today, this will be achieved by creating an `azure_role_assignment` entity, which has relationships to `(azure_user|azure_user_group|azure_service_principal)`, `azure_role_definition` and `(azure_subscription|azure_resource_group|azure_resource)`.

**Comment by aiwilliams** [comment]
Things I learned in our meeting:

* The ingested graph structure should reflect the provider as much as possible. This allows the analyst to work with what is there, not having to figure out some kind of consolidation that we've done, which may prevent analysis we have not anticipated.
* J1QL queries are going to be complex; they pull together current configurations to paint a picture of what is going on. The graph represents the configuration, the queries expose the end state.

The graph we want to build:

* {Principal} <- ASSIGNED - RoleDefinition (collapsed to a single relationship, with a `scopes: string[]` property)
* RoleDefinition - HAS -> RoleAssignment (`_type: "azure_role_assignment"`)
* {Principal} - HAS -> RoleAssignment
* RoleAssignment - ALLOWS -> {Scope} (a relationship that includes the actions relevant to the scope)

Additionally:

* RoleDefinition should have `_class: ["UserRole", "Configuration"]`
* RoleDefinition actions should be transferred to the RoleAssignments (denormalized, to support queries of assignments with certain actions)
* RoleAssignment should have `scope: string` property, `class: ["AccessPolicy"]`
