### ISSUE TITLE
Security Groups cannot create `DENIES` relationships

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#132]
Upgrading the SDK to v3.0.0 introduces type checking for relationship `_class`. The azure integration was previously using the `Denies` relationship class for certain relationships between security groups.

https://github.com/JupiterOne/graph-azure/blob/60a345e699b919812185f24eacaef96de4678b59/src/steps/resource-manager/network/converters/securityGroups.ts#L87

In order to complete the major version bump, I'm going to remove the `DENIES` relationships in security groups. However, It'd be great to add the `DENIES` type to the SDK and add these relationships back in the future.

**Comment by aiwilliams** [comment]
@ndowmon I think we should complete that immediately after the upgrade and before releasing to prod so that folks who might have alerts monitoring their firewalls (security groups) don't get alerted that things are gone. Does that make sense?

**Comment by ndowmon** [comment]
@aiwilliams Yes, that's a very good point. I'll do this first after 3.0.0
