### ISSUE TITLE
Upgade to SDK 3.3.0 & make new `TargetEntity` type compliant

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#169]
When upgrading the SDK to v3.3.0, the Azure integration throws a typescript compile error:

![image](https://user-images.githubusercontent.com/15333061/94384646-18f95f80-0111-11eb-96bb-9ee3c5b01ff3.png)

**Comment by aiwilliams** [comment]
I ran into this today in the Qualys integration! I worked around it because I must focus on getting this thing running, but I'm glad to see it wasn't me holding it wrong.
