### ISSUE TITLE
Can't Retrieve Diagnostic Settings For Azure Storage Resources

### ISSUE THREAD

**Issue by KeionneDerousselle** [JupiterOne/graph-azure#208]
We are currently unable to retrieve Diagnostic Settings for Azure Storage resources (Tables, Queues, Blobs, File Shares). Retrieving Diagnostic Settings for Azure Storage resources is needed to complete CIS Benchmark 3.3, _Ensure Storage logging is enabled for Queue service for read, write, and delete requests (Manual)_. 

This benchmark requires that you ensure that the Diagnostic Settings for Storage Queues has a `Status` that is set to `Off` and it's `Queue Properties` include `Read`, `Write`, and `Delete` under the Logging section. 

These settings and properties are listed in the `classic` version of Diagnostic Settings. 

<img width="824" alt="Screen Shot 2021-01-12 at 12 20 59 PM" src="https://user-images.githubusercontent.com/6044786/104362391-0133c480-54d1-11eb-9297-4fa1d408f1ac.png">

We were unable to find an npm package (Azure Client) that allows us to retrieve `classic` Diagnostic Settings for Azure Storage resources. We were also unable to find a way to create `classic` Diagnostic Settings using Terraform for Azure resources. 

It seems as though the `classic` Diagnostic Settings are being phased out in favor of new Diagnostic Settings. Azure is calling these settings `preview` Diagnostic Settings. 

<img width="881" alt="Screen Shot 2021-01-12 at 12 25 17 PM" src="https://user-images.githubusercontent.com/6044786/104362836-87500b00-54d1-11eb-999f-0173c9d34a2a.png">

These 'preview' settings seem to be the same version of Diagnostic Settings that we were able to successfully retrieve for other Azure resources to complete other CIS Benchmarks, and come from the same Azure Monitor Client that we've been using. 

When attempting to use [Terraform](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting) to create `preview` Diagnostic Settings for Azure Storage resources, as we've successfully done for other Azure resources, we received the following errors.

<img width="1131" alt="Screen Shot 2020-12-31 at 1 38 46 PM" src="https://user-images.githubusercontent.com/6044786/104363029-d72ed200-54d1-11eb-87a3-5c373f8555cf.png">

This is odd, considering that [Azure's documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/resource-logs-categories#microsoftsqlserversdatabases) says that the newer, `preview` version of Diagnostic Settings are supported for Azure Storage Resources. 

<img width="750" alt="Screen Shot 2020-12-31 at 1 38 12 PM" src="https://user-images.githubusercontent.com/6044786/104363036-dbf38600-54d1-11eb-9c6b-53ee4f1fd0e9.png">

It may be that Terraform does not yet support the creation of `preview` Diagnostic Settings for Azure Storage resources, even though it supports the creation of Diagnostic Settings for other Azure resources.

Until we are able to find an Azure client that allows us to retrieve `classic` Diagnostic Settings, or Terraform allows us to create `preview` Diagnostics Settings for Azure Storage resources, we may not be able to complete or test CIS Benchmark 3.3, _Ensure Storage logging is enabled for Queue service for read, write, and delete requests (Manual)_.

**Comment by ndowmon** [comment]
The `Diagnostic settings (classic)` properties required for CIS Benchmark 3.3 actually refer to "Storage Analytics"(<https://docs.microsoft.com/en-us/azure/storage/common/storage-analytics>), a completely different concept than the "Diagnostic Settings" used throughout the Azure platform. These are accessed through a different API, which is why collecting diagnostic settings threw errors in these cases.

They have been added in #237 and #238 .
