### ISSUE TITLE
Ingest Azure VM Firewall Rules

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#338]
Under the **Networking** blade of Azure Virtual Machines.

<img width="856" alt="Screen Shot 2021-05-17 at 12 13 49 PM" src="https://user-images.githubusercontent.com/15333061/118521758-57c44000-b709-11eb-9bac-9d1519607b05.png">

It would be great to create a new J1 `_class` for `FirewallRule` and use that here: https://github.com/JupiterOne/data-model/issues/70

**Comment by kenanwarren** [comment]
So I think we only need a new relationship from a VM to a NIC. The NIC has a mapping to a NSG which has a relationship to the rules.

**Comment by kenanwarren** [comment]
Already done within the project through azure_vm -> azure_nic relationships
