### ISSUE TITLE
Ingest User MFA Status

### ISSUE THREAD

**Issue by ndowmon** [JupiterOne/graph-azure#346]
https://graph.microsoft.com/v1.0/users/{{user-id}}/authentication/microsoftAuthenticatorMethods

https://docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&tabs=http

**Comment by ndowmon** [comment]
Example response:

```
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users('184bb7d9-1fab-4e08-8cf5-d618a22e2873')/authentication/microsoftAuthenticatorMethods",
  "value": [
    {
      "id": "c9928d82-e10b-4e80-a272-6809c8ab0c69",
      "displayName": "Nick’s iPhone",
      "deviceTag": "SoftwareTokenActivated",
      "phoneAppVersion": "6.5.38",
      "createdDateTime": null
    }
  ]
}
```

**Comment by ndowmon** [comment]
Not actually sure that this endpoint reliably finds MFA status. Seems that after disabling MFA on a certain user, the API continues to return data, because the auth method is still setup.

**Comment by ndowmon** [comment]
One way we _can_ get MFA status is using powershell: https://dailysysadmin.com/KB/Article/3725/use-powershell-to-get-the-mfa-enabled-or-disabled-status-of-office-365-and-azure-users-and-type-of-mfa-used/

```powershell
PS /> Install-Module MSOnline
PS /> Connect-MsolService
PS /> Get-MsolUser
```

Unfortunately, although Microsoft has published both linux & windows base images for Powershell, we are not able to use the linux images to run `Connect-MsolService` because PowerShell Core does not support the `System.IdentityModel` package required to call this cmdlet.

https://github.com/PowerShell/PowerShell/issues/10818
https://github.com/PowerShell/PowerShell/issues/7162

Hence, this _seems_ like it will not be able to run in the same compute environment that the Azure integration runs on.

**Comment by ndowmon** [comment]
@kenanwarren thanks for finding this endpoint in the beta graph API: https://docs.microsoft.com/en-us/graph/api/reportroot-list-credentialuserregistrationdetails?view=graph-rest-beta&tabs=http

This may allow us to fetch MFA info for some customers. However, it does require an Active Directory premium tier 1 license: https://docs.microsoft.com/lv-lv/azure/active-directory/reports-monitoring/troubleshoot-graph-api

See local response:
```
{
  "error": {
    "code": "Authentication_RequestFromNonPremiumTenantOrB2CTenant",
    "message": "Neither tenant is B2C or tenant doesn't have premium license",
    "innerError": {
      "date": "2021-05-19T14:44:47",
      "request-id": "39e47486-23ac-4a7b-af5c-498fa89971c5",
      "client-request-id": "39e47486-23ac-4a7b-af5c-498fa89971c5"
    }
  }
}
```

**Comment by kenanwarren** [comment]
Waiting to test the reports endpoint, I've setup P2 and B2C Azure AD instances. Currently the reports endpoint is returning no users, which after some digging could be:

1. The reports aren't updated when you hit the endpoint, there might be some time delay [(seen mentions of 48-72 hours)](https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reports-faq).
2. Users on the old MFA system don't show up in the API, couldn't find a MSFT source for this.

If this doesn't work on Monday, we might need to decide if the Window PowerShell option is worth doing. @ndowmon if you want an invite to that azure setup let me know.

**Comment by kenanwarren** [comment]
**_To get the data I ended up needing to kick the tires of the report by doing three things:_**


### 1. I made a conditional access policy for a fake MFA pilot, I followed these [instructions](https://docs.microsoft.com/en-us/azure/active-directory/authentication/tutorial-enable-azure-mfa).
<img width="915" alt="Screen Shot 2021-05-24 at 10 32 32 AM" src="https://user-images.githubusercontent.com/552305/119363034-5d76d400-bc7b-11eb-9ac0-f1330d157054.png">


### 2. I created a new AD security group and used it to assign licenses to my users. I tried using the old o365 interface to assign licenses on Friday, but that didn't work.
<img width="921" alt="Screen Shot 2021-05-24 at 10 31 19 AM" src="https://user-images.githubusercontent.com/552305/119362931-3e784200-bc7b-11eb-9ff6-e930ebc8da10.png">
<img width="920" alt="Screen Shot 2021-05-24 at 10 31 10 AM" src="https://user-images.githubusercontent.com/552305/119362945-4506b980-bc7b-11eb-9abe-3929e8ad875d.png">


### 3. I enabled a few different access policies under "Authentication Methods". (I'm not certain if this one contributed to it, but was one of the last things I did.)
<img width="906" alt="Screen Shot 2021-05-24 at 10 33 42 AM" src="https://user-images.githubusercontent.com/552305/119363221-8eef9f80-bc7b-11eb-844f-b0f504b35a1d.png">

**Comment by kenanwarren** [comment]
It might be easier to use these reports if you're using a more traditional business tenant. My tenant had a few weird things going on in general (o365 admin takeover, using a number of free trials, etc).
